name: Lint

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Code linting

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.21
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Update pip and install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install check-manifest flake8

      - name: Check MANIFEST.in in a source package
        run: check-manifest -v

      - name: Static code analysis and code style check
        run: flake8 ./
